---
- name: get pa-tg source (local checkout)
  local_action:
    module: git
    repo: https://gitlab.com/personal-assistant-bot/infrastructure/pa-tg.git
    version: "{{ tg_version }}"
    dest: tmp/pa-tg

- name: upload pa-tg source
  synchronize:
    src: tmp/pa-tg/
    dest: /var/pa
    delete: yes
  register: tg

- name: install dependencies
  pip:
    requirements: /var/pa/requirements.txt

- name: upload service file
  copy:
    src: files/pa.service
    dest: /etc/systemd/system/
  register: unit

- name: upload token file
  copy:
    src: files/token.txt
    dest: /var/pa-token.txt
  register: token

- name: reload systemd unit
  systemd:
    daemon_reload: yes
  when: unit.changed

- name: start the service
  service:
    name: pa
    state: started
    enabled: yes

- name: restart service if new version is deployed
  service:
    name: pa
    state: restarted
    enabled: yes
  when: tg.changed or unit.changed or token.changed