---
- name: get pa-tg source (local checkout)
  local_action:
    module: git
    repo: https://gitlab.com/personal-assistant-bot/infrastructure/pa-tg.git
    version: "{{ tg_version }}"
    dest: tmp/pa-tg
  register: tg

- name: upload pa-tg source
  synchronize:
    src: tmp/pa-tg/
    dest: /var/pa
    delete: yes
  notify:
  - install dependencies
  - update hash
  - restart server
  when: ansible_local.tg.hash|default('') != tg.after

- name: patch stomp
  include_tasks: tasks/stomp.yml

- name: upload service file
  copy:
    src: files/pa.service
    dest: /etc/systemd/system/
  notify: reload systemd unit

- name: upload token file
  copy:
    src: files/token.txt
    dest: /var/pa-token.txt
  notify: restart server

- name: install xtomp server
  import_tasks: xtomp.yml

- name: set up xtomp-user account
  import_tasks: user.yml

- name: ensure service is started
  service:
    name: pa
    state: started
    enabled: yes
