---
- name: check requirements
  shell: grep stomp.py /var/pa/requirements.txt
  register: got_stomp
  ignore_errors: true
  args:
    warn: no

- name: apply patch
  patch:
    src: files/stomp.patch
    dest: /usr/local/lib/python3.7/dist-packages/stomp/transport.py
  when: got_stomp.rc == 0
