---
- name: create xtomp-user user
  user:
    name: xtomp-user
    state: present
    shell: /opt/xtomp-user/shell
    home: /opt/xtomp-user

- name: upload shell entrypoint
  copy:
    src: files/shell.sh
    dest: /opt/xtomp-user/shell
    mode: '500'
    owner: xtomp-user

- name: disable ssh banner for xtomp-user
  file:
    path: /opt/xtomp-user/.hushlogin
    state: touch
    owner: xtomp-user
    group: xtomp-user
    modification_time: preserve
    access_time: preserve

- name: set ssh key to xtomp-user
  authorized_key:
    user: xtomp-user
    key: "{{ lookup('file', 'xtomp-user.key.pub') }}"