---
- name: make facts directory
  file:
    state: directory
    dest: /etc/ansible/facts.d

- name: write hash of installed pa-tg
  copy:
    content: "{\"hash\": \"{{ tg.after }}\"}"
    dest: /etc/ansible/facts.d/tg.fact

- name: write hash of installed stomp
  copy:
    content: "{\"hash\": \"{{ stomp.after }}\"}"
    dest: /etc/ansible/facts.d/stomp.fact
