---
- name: install xtomp
  block:
  - name: install dependencies
    apt:
      name: ['libaio1', 'socat']
      state: present

  - name: Check if xtomp is installed
    command: dpkg-query -W xtomp
    register: xtomp_check_deb
    failed_when: xtomp_check_deb.rc > 1
    changed_when: xtomp_check_deb.rc == 1

  - name: install xtomp
    apt:
      deb: http://download.tp23.org/download/deb/xtomp-0.3-1.x86_64.deb
    when: xtomp_check_deb.rc == 1

- name: upload xtomp configuration
  copy:
    src: files/xtomp.conf
    dest: /etc/
  notify: restart xtomp

- name: ensure xtomp service is started
  service:
    name: xtomp
    state: started
    enabled: yes
