---
- name: Setup python
  hosts: all
  gather_facts: no
  tasks:
  - name: update apt
    raw: apt-get update
  - name: install python3
    raw: apt-get -y install --no-install-recommends python3

- name: Setup requirements
  hosts: all
  tasks:
  - name: install python pip
    block:
    - name: install pip
      apt:
        name: python3-pip
        install-recommends: no
        state: present
    - name: install pkg-resources
      apt:
        name: python3-pkg-resources
        state: present
    - name: install setuptools
      pip:
        name: setuptools
        state: present
  - name: install utils
    apt:
      name: ['rsync', 'patch']
      state: present