---
- name: install dependencies
  pip:
    requirements: /var/pa/requirements.txt
  notify: patch stomp

# include_tasks is a workaround -- can't use block in handlers
- name: update tg hash
  include_tasks: tasks/write_hash.yml

- name: patch stomp
  include_tasks: tasks/patch_stomp.yml

- name: reload systemd unit
  systemd:
    daemon_reload: yes
  notify: restart server

- name: restart xtomp
  service:
    name: xtomp
    state: restarted
    enabled: yes

- name: restart server
  service:
    name: pa
    state: restarted
    enabled: yes
