---
- name: reload systemd unit
  systemd:
    daemon_reload: yes
  when: unit.changed
  notify: restart server

- name: restart server
  service:
    name: pa
    state: restarted
    enabled: yes

- name: update installed tg hash
  block:
  - name: make facts directory
    file:
      state: directory
      dest: /etc/ansible/facts.d

  - name: write hash of installed pa-tg
    copy:
      content: "{\"tg_hash\": \"{{ tg.after }}\"}"
      dest: /etc/ansible/facts.d/tg.fact
