---
- name: install dependencies
  pip:
    requirements: /var/pa/requirements.txt
  notify: patch stomp

# include_tasks is a workaround -- can't use block in handlers
- name: update tg hash
  include_tasks: tasks/write_hash.yml

- name: patch stomp
  patch:
    src: files/stomp.patch
    dest: /usr/local/lib/python3.7/dist-packages/stomp/transport.py

- name: reload systemd unit
  systemd:
    daemon_reload: yes
  notify: restart server

- name: restart server
  service:
    name: pa
    state: restarted
    enabled: yes
