---
- name: install dependencies
  pip:
    requirements: /var/pa/requirements.txt

# include_tasks is a workaround -- can't use block in handlers
- name: update tg hash
  include_tasks: tasks/write_hash.yml

- name: reload systemd unit
  systemd:
    daemon_reload: yes
  notify: restart server

- name: restart server
  service:
    name: pa
    state: restarted
    enabled: yes
